name: nico
recipe: drupal8

config:
  php: '7.2'
  webroot: web
  xdebug: true
  conf:
    # Tell Lando to use additional PHP settings.
    # The location of this file is arbitrary.
    # We placed it inside .vscode/ folder simply because we find it convenient.
    php: .vscode/php.ini

# Provide nice url's
proxy:
  mailhog:
    - mail.drupal8.lndo.site
  pma:
    - pma.drupal8.lndo.site

services:
  ## MailHog
  # -----------
  mailhog:
    # Use the latest mailhog version
    type: mailhog
    # List of services that we want to capture mail from
    # You can run `lando info` to get a list of services that are available
    # Mailhog expects that these services will be php services
    hogfrom:
      - appserver
    # Optionally allow access to the smtp service at localhost:1026
    # You will need to make sure port 1026 is open on your machine
    #
    # You can also set `portforward: true` to have Lando dynamically assign
    # an open port. Unlike specifying an actual port setting this to true will give you
    # a different port every time you restart your app
    portforward: 1026
  ## PhpMyAdmin
  # -----------
  pma:
    type: phpmyadmin
    hosts:
      - database
